# Generated by Django 3.0.5 on 2020-04-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LookupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='media',
        ),
        migrations.DeleteModel(
            name='FacilitySubType',
        ),
        migrations.DeleteModel(
            name='FacilityType',
        ),
        migrations.AddField(
            model_name='lookup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionLibrary.LookupGroup'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='QuestionLibrary.LookupGroup'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medias', to='QuestionLibrary.LookupGroup'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='response_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_types', to='QuestionLibrary.LookupGroup'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='QuestionLibrary.LookupGroup'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='ResponseType',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
