# Generated by Django 3.0.5 on 2020-04-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0003_auto_20200420_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitySubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='masterquestion',
            name='lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.LookupGroup'),
        ),
        migrations.AlterField(
            model_name='lookupgroup',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Category'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Media'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='response_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.ResponseType'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Unit'),
        ),
    ]
