# Generated by Django 3.0.5 on 2020-04-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0005_auto_20200420_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitytype',
            name='sub_type',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_facility_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.FacilitySubType'),
            preserve_default=False,
        ),
    ]
