# Generated by Django 3.0.5 on 2020-04-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0006_auto_20200420_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterquestion',
            name='question',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Unit'),
        ),
    ]
