# Generated by Django 3.0.5 on 2020-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0007_auto_20200420_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='facility_field',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='map_service',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='media_field',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='service_config',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='sub_facility_field',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
