# Generated by Django 3.0.5 on 2020-04-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0008_auto_20200420_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetype',
            name='survey123_field_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lookup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookups', to='QuestionLibrary.LookupGroup'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='QuestionLibrary.Survey'),
        ),
    ]
