# Generated by Django 3.0.7 on 2020-06-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0009_auto_20200420_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterquestion',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
