# Generated by Django 3.0.7 on 2020-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0010_auto_20200608_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
