# Generated by Django 3.0.7 on 2020-06-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0011_survey_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
