# Generated by Django 3.0.7 on 2020-06-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0010_auto_20200608_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.MasterQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Assessment'},
        ),
        migrations.AddField(
            model_name='questionlist',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.QuestionSet'),
        ),
    ]
