# Generated by Django 3.0.7 on 2020-06-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0012_surveyquestion_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Assessment'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='question',
        ),
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.MasterQuestion', unique=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.QuestionSet', unique=True)),
            ],
        ),
    ]
