# Generated by Django 3.0.7 on 2020-06-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0013_auto_20200610_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.QuestionSet', unique=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Survey')),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
    ]
