# Generated by Django 3.0.7 on 2020-06-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0014_auto_20200610_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='question_set', to='QuestionLibrary.Survey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyquestionset',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='QuestionLibrary.Survey'),
        ),
    ]
