# Generated by Django 3.0.7 on 2020-06-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0015_auto_20200617_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(related_name='question_set', through='QuestionLibrary.QuestionList', to='QuestionLibrary.MasterQuestion'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='surveys',
            field=models.ManyToManyField(related_name='question_set', to='QuestionLibrary.Survey'),
        ),
    ]
