# Generated by Django 3.0.7 on 2020-06-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0016_auto_20200617_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureServiceResponseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esri_field_type', models.CharField(max_length=250)),
                ('fs_response_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.FeatureServiceResponseType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='survey',
            name='service_config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
    ]
