# Generated by Django 3.0.7 on 2020-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0017_auto_20200625_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSResponseLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs_response_type', models.CharField(max_length=250)),
                ('esri_field_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='FeatureServiceResponseType',
        ),
    ]
