# Generated by Django 3.0.7 on 2020-06-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0018_auto_20200625_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FSResponseLookup',
            new_name='FeatureServiceResponse',
        ),
    ]
