# Generated by Django 3.0.7 on 2020-06-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0019_auto_20200625_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='facility_field',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='media_field',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='sub_facility_field',
        ),
        migrations.AddField(
            model_name='survey',
            name='facility_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.FacilityType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='sub_facility_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.FacilitySubType'),
            preserve_default=False,
        ),
    ]
