# Generated by Django 3.0.7 on 2020-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0020_auto_20200626_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
