# Generated by Django 3.0.7 on 2020-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0021_questionset_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='questionlist',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
