# Generated by Django 3.0.7 on 2020-07-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0024_auto_20200629_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='facility_type',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='media',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='sub_facility_type',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey123_service',
            field=models.URLField(null=True),
        ),
    ]
