# Generated by Django 3.0.7 on 2020-07-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0025_auto_20200707_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Assessment'},
        ),
        migrations.RemoveField(
            model_name='masterquestion',
            name='question_active',
        ),
    ]
