# Generated by Django 3.0.7 on 2020-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0026_auto_20200707_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterquestion',
            old_name='units',
            new_name='default_unit',
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(help_text='This is a test', max_length=50),
        ),
        migrations.AlterField(
            model_name='facilitysubtype',
            name='label',
            field=models.CharField(help_text='This is a test', max_length=50),
        ),
        migrations.AlterField(
            model_name='facilitytype',
            name='label',
            field=models.CharField(help_text='This is a test', max_length=50),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='label',
            field=models.CharField(help_text='This is a test', max_length=50),
        ),
        migrations.AlterField(
            model_name='lookupgroup',
            name='label',
            field=models.CharField(help_text='This is a test', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='label',
            field=models.CharField(help_text='This is a test', max_length=50),
        ),
        migrations.AlterField(
            model_name='responsetype',
            name='label',
            field=models.CharField(help_text='This is a test', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='label',
            field=models.CharField(help_text='This is a test', max_length=50),
        ),
    ]
