# Generated by Django 3.0.7 on 2020-07-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0027_auto_20200707_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterquestion',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Lookup'),
        ),
    ]
