# Generated by Django 2.2.15 on 2020-08-12 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0028_auto_20200707_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='selected_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='default_unit',
            field=models.ForeignKey(blank=True, help_text='To set a default vales ..... etc', null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Lookup'),
        ),
    ]
