# Generated by Django 2.2.15 on 2020-08-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0029_auto_20200811_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='layer_choice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey123_service',
            field=models.URLField(blank=True, null=True),
        ),
    ]
