# Generated by Django 2.2.15 on 2020-09-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0030_auto_20200827_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='layer_choice',
            new_name='layer',
        ),
    ]
