# Generated by Django 2.2.15 on 2020-09-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0031_auto_20200903_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='facility_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_facility_type',
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Category'),
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='facility_type',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='FacilitySubType',
        ),
    ]
