# Generated by Django 2.2.15 on 2020-09-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0032_auto_20200925_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterquestion',
            name='facility_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.FacilityType'),
            preserve_default=False,
        ),
    ]
