# Generated by Django 2.2.15 on 2020-09-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0033_masterquestion_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterquestion',
            name='facility_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.FacilityType'),
        ),
    ]
