# Generated by Django 2.2.15 on 2020-10-08 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0035_auto_20200925_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Category'),
        ),
    ]
