# Generated by Django 2.2.15 on 2020-11-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0036_auto_20201007_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lookupgroup',
            options={'verbose_name': 'Response Type'},
        ),
        migrations.AlterModelOptions(
            name='responsetype',
            options={'verbose_name': 'ESRI Response Type'},
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(help_text='like this', max_length=50),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='label',
            field=models.CharField(help_text='like this', max_length=50),
        ),
        migrations.AlterField(
            model_name='lookupgroup',
            name='label',
            field=models.CharField(help_text='like this', max_length=50),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='default_unit',
            field=models.ForeignKey(blank=True, help_text='To generate a list of default values, select desired response type and click "Save and Continue Editing"', null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Lookup'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.LookupGroup', verbose_name='Response Type'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='response_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.ResponseType', verbose_name='Survey123 Field Type'),
        ),
        migrations.AlterField(
            model_name='media',
            name='label',
            field=models.CharField(help_text='like this', max_length=50),
        ),
        migrations.AlterField(
            model_name='responsetype',
            name='label',
            field=models.CharField(help_text='like this', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='label',
            field=models.CharField(help_text='like this', max_length=50),
        ),
    ]
