# Generated by Django 2.2.15 on 2021-01-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0038_auto_20210111_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='questionset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Category'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='facility_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.FacilityType'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.Media'),
        ),
    ]
