# Generated by Django 2.2.15 on 2021-01-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0042_auto_20210126_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterquestion',
            name='related_questions',
            field=models.ManyToManyField(related_name='related_question', through='QuestionLibrary.RelatedQuestionList', to='QuestionLibrary.MasterQuestion'),
        ),
        migrations.AlterField(
            model_name='relatedquestionlist',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_questions', to='QuestionLibrary.MasterQuestion'),
        ),
        migrations.DeleteModel(
            name='RelatedQuestion',
        ),
    ]
