# Generated by Django 2.2.28 on 2023-05-23 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid

def set_true_unique_ids(apps, schema_editor):
    MasterQuestion = apps.get_model('QuestionLibrary', 'MasterQuestion')
    for x in MasterQuestion.objects.all():
        x.unique_id = uuid.uuid4()
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0043_auto_20210126_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterquestion',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4()),
        ),
        migrations.RunPython(set_true_unique_ids, migrations.RunPython.noop)
    ]
