# Generated by Django 3.2.19 on 2023-06-08 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0045_auto_20230601_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
