# Generated by Django 3.1.14 on 2023-11-29 18:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0047_base_epa_response_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='facility_type',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='media',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='assessment_layer',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='base_map_service',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='service_config',
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='default_unit',
            field=models.ForeignKey(blank=True, help_text='To generate a list of default values, select desired answer type and click "Save and Continue Editing"', null=True, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.lookup'),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b2fc79ed-5f23-4f06-9c2a-608b2663052c')),
        ),
        migrations.AlterField(
            model_name='survey',
            name='epa_response',
            field=models.ForeignKey(blank=True, help_text='Select an active EPA response and click "Save and Continue Editing" before proceeding.', limit_choices_to={'disabled_date': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuestionLibrary.eparesponse'),
        ),
    ]
