# Generated by Django 4.2.9 on 2024-01-19 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0048_auto_20231129_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterquestion',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('5bbc02c3-e48b-41f8-ae8c-6d65af6d3451')),
        ),
    ]
