# Generated by Django 4.2.9 on 2024-01-24 23:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionLibrary', '0049_alter_masterquestion_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(help_text='This will be what users see.', max_length=50),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='label',
            field=models.CharField(help_text='This will be what users see.', max_length=50),
        ),
        migrations.AlterField(
            model_name='lookupgroup',
            name='label',
            field=models.CharField(help_text='This will be what users see.', max_length=50),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='survey123_field_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='QuestionLibrary.survey123fieldtype', verbose_name='Survey123 Field Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('13e2d61b-e5d4-4261-abdb-60efc323e88a')),
        ),
        migrations.AlterField(
            model_name='media',
            name='label',
            field=models.CharField(help_text='This will be what users see.', max_length=50),
        ),
        migrations.AlterField(
            model_name='survey123fieldtype',
            name='label',
            field=models.CharField(help_text='This will be what users see.', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='label',
            field=models.CharField(help_text='This will be what users see.', max_length=50),
        ),
    ]
